server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aa
    username: aa
    password: s3cr3t
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format_sql: false
    show-sql: false

kafka:
  servers: localhost:9092
  topic: auth.accounts